-- DEPRECATED: This file has been moved to 20260324_007_invoice_number_unique.sql
-- Reason: Duplicate migration number (009) conflict with 009_add_counterpart_iban.sql
-- Please run the new file instead.
